# .github/workflows/build_windows.yml
name: Build & Release Windows

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv & Python 3.10
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.2"
          python-version: "3.10"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          prune-cache: true

      - name: Build with build.bat
        # habilita comandos extendidos y expansión retardada
        shell: cmd /E:ON /V:ON {0}
        run: |
          call build.bat

      - name: Upload Windows distributable
        uses: actions/upload-artifact@v4
        with:
          name: windows-dist
          path: dist/AutomationPanel-windows/**

  release:
    name: Draft GitHub prerelease
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Windows distributable
        uses: actions/download-artifact@v4
        with:
          name: windows-dist
          path: release-assets/AutomationPanel-windows

      - name: Zip source code
        run: |
          zip -r release-assets/source.zip . \
            -x ".git/*" "dist/*" "build/*" ".venv/*" "logs/*"

      - name: Publish GitHub prerelease
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: build-${{ github.run_number }}
          prerelease: true
          files: |
            release-assets/AutomationPanel-windows/**
            release-assets/source.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
