name: PyInstaller Auto-Release

on:
  push:
    branches:
      - master  # trigger on master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install project & PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pyinstaller

      - name: Build binary
        run: |
          pyinstaller --noconfirm --onefile app.py --name AutomationPanel

      - name: Rename binary
        run: |
          TIMESTAMP=$(date +"%Y%m%d-%H%M%S")
          echo "RELEASE_NAME=build-${TIMESTAMP}" >> $GITHUB_ENV
          mkdir release
          mv dist/AutomationPanel release/AutomationPanel-linux

      - name: Create GitHub Release (auto-named)
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.RELEASE_NAME }}
          prerelease: true
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
