name: Build and Release

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install global dependencies
        if: matrix.os == 'windows-latest'
        run: |
          python -m pip install --upgrade pip
          pip install uv
        shell: bash

      - name: Create and seed virtual environment (Windows)
        if: matrix.os == 'windows-latest'
        run: uv venv --seed
        shell: bash

      - name: Activate venv (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          .\.venv\Scripts\activate
        shell: powershell

      - name: Sync dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: uv sync
        shell: bash

      - name: Install build tools
        if: matrix.os == 'windows-latest'
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
        shell: bash

      - name: Build with build.bat (Windows)
        if: matrix.os == 'windows-latest'
        run: .\build.bat
        shell: cmd

      - name: Install project & PyInstaller (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pyinstaller
        shell: bash

      - name: Build binary (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pyinstaller --noconfirm --onefile app.py --name AutomationPanel
        shell: bash

      - name: Collect artifacts
        run: |
          mkdir upload
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            mv dist/AutomationPanel-windows.exe upload/AutomationPanel-windows.exe
          else
            mv dist/AutomationPanel upload/AutomationPanel-linux
          fi
        shell: bash

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.os }}
          path: upload/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: binaries-*
          path: release-assets
          merge-multiple: true

      - name: Set release name
        id: rel
        run: echo "name=build-$(date +'%Y%m%d-%H%M%S')" >> "$GITHUB_OUTPUT"

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.rel.outputs.name }}
          name: ${{ steps.rel.outputs.name }}
          prerelease: true
          files: release-assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
