name: PyInstaller Auto-Release

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    env:
      APP_NAME_WINDOWS: AutomationPanel-windows
      APP_NAME_LINUX: AutomationPanel-linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install uv globally
        run: python -m pip install --upgrade pip uv

      - name: Create & seed venv
        run: uv venv --seed

      - name: Sync project dependencies
        run: uv sync

      - name: Activate venv & install build tools
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            VENV_BIN="$PWD/.venv/Scripts"
          else
            VENV_BIN="$PWD/.venv/bin"
          fi
          export PATH="$VENV_BIN:$PATH"
          pip install --upgrade pip pyinstaller

      - name: Build with PyInstaller
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            NAME="$APP_NAME_WINDOWS"
          else
            NAME="$APP_NAME_LINUX"
          fi
          python -m PyInstaller \
            --noconsole \
            --onedir \
            --name "$NAME" \
            --hidden-import=playwright_stealth \
            --hidden-import=patchright \
            --hidden-import=psutil \
            --hidden-import=tkinter \
            --hidden-import=customtkinter \
            app.py

      - name: Rename & collect artifact
        shell: bash
        run: |
          mkdir upload
          if [ "${{ runner.os }}" = "Windows" ]; then
            mv "dist/$APP_NAME_WINDOWS" upload/
          else
            mv "dist/$APP_NAME_LINUX" upload/
          fi

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ runner.os }}
          path: upload/*
