name: PyInstaller Auto-Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

env:
  UV_LINK_MODE: copy

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install uv CLI
        shell: cmd
        run: python -m pip install --upgrade pip uv

      - name: Build with build.bat
        shell: cmd
        run: .\build.bat

      - name: Upload Windows distributable
        uses: actions/upload-artifact@v4
        with:
          name: AutomationPanel-windows
          path: dist/AutomationPanel-windows/**

  release:
    needs: build_windows
    runs-on: ubuntu-latest

    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: AutomationPanel-windows
          path: release-assets

      - name: Generate release tag
        id: rel
        run: echo "name=build-$(date +'%Y%m%d-%H%M%S')" >> "$GITHUB_OUTPUT"

      - name: Publish GitHub prerelease
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.rel.outputs.name }}
          name: ${{ steps.rel.outputs.name }}
          prerelease: true
          files: release-assets/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
