name: Windows PyInstaller Build with uv

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.2"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Python via uv
        run: uv python install

      # ← NEW STEP: generate uv.lock
      - name: Generate uv.lock
        run: uv lock

      - name: Sync dependencies (locked)
        run: uv sync --locked

      - name: Install PyInstaller
        run: uv pip install --upgrade pyinstaller

      - name: Clean dist & build
        shell: cmd
        run: |
          if exist dist\AutomationPanel-windows rmdir /S /Q dist\AutomationPanel-windows
          if exist build rmdir /S /Q build
          if exist AutomationPanel-windows.spec del AutomationPanel-windows.spec

      - name: Run PyInstaller
        shell: cmd
        run: uv run python -m PyInstaller ^
          --noconsole ^
          --onedir ^
          --name AutomationPanel-windows ^
          --hidden-import=playwright_stealth ^
          --hidden-import=patchright ^
          --hidden-import=psutil ^
          --hidden-import=tkinter ^
          --hidden-import=customtkinter ^
          app.py

      - uses: actions/upload-artifact@v4
        with:
          name: AutomationPanel-windows
          path: dist/AutomationPanel-windows
