#NOTE : successfully tested on in 506d4dfd7d379eb6fcf22c62a6485ba6b4ff2495 - 05/03/2025

name: Windows Build with PyInstaller & UV

on:
  push:
    branches:
      - master
      - dev-main

    paths:
      - 'app/**'
      - 'pyproject.toml'
      - 'build.bat'
      - 'start.bat'
      - 'AutomationPanel-windows.spec'
      - 'README.md'
      
  workflow_dispatch:

jobs:
  build:
    name: Build Windows EXE
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install UV CLI
        run: pip install uv

      - name: Create and sync virtual environment
        run: |
          uv venv --seed
          uv sync

      - name: Install Playwright browsers
        run: |
          .\.venv\Scripts\activate
          python -m playwright install --with-deps

      - name: Install PyInstaller
        run: .\.venv\Scripts\pip install pyinstaller

      - name: Build with PyInstaller using .spec
        run: |
          .\.venv\Scripts\pyinstaller AutomationPanel-windows.spec

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutomationPanel-windows-${{ github.ref_name }}
          path: dist/AutomationPanel-windows/**
