name: Build and Package Automation Panel

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv CLI and Python
        uses: astral-sh/setup-uv@v5
        with:
          # detect Python version from .python-version
          python-version-file: ".python-version"

      - name: Create venv & sync dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          uv venv --seed
          uv sync --locked

      - name: Create venv & sync dependencies (Windows)
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          uv venv --seed
          uv sync --locked

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build single-file Linux binary
        if: matrix.os == 'ubuntu-latest'
        run: |
          pyinstaller --noconfirm \
            --onefile \
            --name AutomationPanel \
            app.py

      - name: Build Windows directory package
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          pyinstaller --noconfirm --onedir `
            --name AutomationPanel-windows `
            --hidden-import=playwright_stealth `
            --hidden-import=patchright `
            --hidden-import=psutil `
            --hidden-import=tkinter `
            --hidden-import=customtkinter `
            app.py

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.os }}
          path: |
            dist/AutomationPanel*
            dist/AutomationPanel-windows*
