name: Build & Release (Windows only)

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    name: Build on Windows

    steps:
      - uses: actions/checkout@v4

      - name: Setup uv + Python 3.10
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.2"
          python-version: "3.10"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          prune-cache: true

      - name: Run local build.bat with delayed expansion
        shell: cmd /E:ON /V:ON {0}
        run: |
          call build.bat

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: windows-dist
          path: dist/AutomationPanel-windows/**

  release:
    needs: build
    runs-on: ubuntu-latest
    name: Draft GitHub prerelease

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: windows-dist
          path: release-assets/AutomationPanel-windows

      - name: Zip source
        run: |
          zip -r release-assets/source.zip . \
            -x ".git/*" "dist/*" "build/*" ".venv/*" "logs/*"

      - name: Publish prerelease
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: build-${{ github.run_number }}
          prerelease: true
          files: |
            release-assets/AutomationPanel-windows/**
            release-assets/source.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
