name: PyInstaller Auto-Release

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install project & PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pyinstaller

      - name: Build binary
        run: |
          pyinstaller --noconfirm --onefile app.py --name AutomationPanel

      - name: Rename binary
        shell: bash
        run: |
          mkdir upload
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mv dist/AutomationPanel.exe upload/AutomationPanel-windows.exe
          else
            mv dist/AutomationPanel upload/AutomationPanel-linux
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ runner.os }}
          path: upload/*
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: binaries-*
          path: release-assets
          merge-multiple: true

      - name: Set release name
        id: rel
        run: echo "name=build-$(date +'%Y%m%d-%H%M%S')" >> "$GITHUB_OUTPUT"

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.rel.outputs.name }}
          name: ${{ steps.rel.outputs.name }}
          prerelease: true
          files: release-assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
