name: Lint

on: [push, pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10 with pip cache
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
          cache: pip              # cachea ~/.cache/pip automáticamente :contentReference[oaicite:0]{index=0}

      - name: Install project & pylint
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pylint

      - name: Lint (parallel, no-fail)
        run: |
          # usar todos los núcleos disponibles (-j 0) para speed up :contentReference[oaicite:1]{index=1}
          pylint -j 0 --exit-zero $(git ls-files '*.py')
