name: Lint

on:
  push:
    paths:
      - "**/*.py"
      - "pyproject.toml"
      - "requirements.txt"
      - ".pylintrc"

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml','**/requirements.txt') }}

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pylint

      - name: Cache Pylint cache
        uses: actions/cache@v3
        with:
          path: ~/.pylint.d
          key: ${{ runner.os }}-pylint-${{ hashFiles('**/.pylintrc') }}

      - name: Lint changed files (parallel, no-fail)
        run: |
          # detecta qué .py cambió en este push
          changed=$(git diff --name-only ${{ github.sha }} ${{ github.sha }}^ -- '*.py')
          if [ -n "$changed" ]; then
            echo "Linting only changed files:"
            echo "$changed"
            pylint --exit-zero --jobs=$(nproc) $changed
          else
            echo "No changed .py files detected, linting all:"
            pylint --exit-zero --jobs=$(nproc) $(git ls-files '*.py')
          fi
