name: Lint

on: [push, pull_request]

permissions:
  contents: read
  checks: write

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install project dependencies
        run: |
          uv sync

      - name: Run pylint
        run: |
          echo "::group::📋 Pylint report"
          uv run pylint \
            --rcfile=pyproject.toml \
            --load-plugins=pylint_actions \
            --output-format=github \
            --reports=y \
            $(find . -name "*.py" \
              -not -path "./.venv/*" \
              -not -path "./build/*" \
              -not -path "./dist/*" \
              -not -path "./__pycache__/*")
          echo "::endgroup::"
          echo "✅ Pylint passed" \
            || (echo "❌ Pylint failed"; exit 1)
