# .github/workflows/lint.yml
name: Lint

on:
  push:
    paths:
      - "**/*.py"
      - "pyproject.toml"
      - "uv.lock"
  pull_request:
    paths:
      - "**/*.py"
      - "pyproject.toml"
      - "uv.lock"

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: |
          uv sync
          uv add --dev pylint

      - name: Run pylint
        run: |
          uv run pylint --exit-zero $(find . -name "*.py" -not -path "./.venv/*" -not -path "./build/*" -not -path "./dist/*" -not -path "./__pycache__/*")
