# .github/workflows/ruff.yml
name: Lint with Ruff

on:
  push:
    paths:
      - '**/*.py'
      - 'pyproject.toml'
      - '.ruff.toml'
  pull_request:
    paths:
      - '**/*.py'
      - 'pyproject.toml'
      - '.ruff.toml'

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ruff
        uses: astral-sh/ruff-action@v3.3.0
        with:
          # por defecto hace `ruff check`, aquí explícitamente:
          args: fix .
          # directorio a lintear (puede ser '.' o 'app/' si prefieres)
          src: .
          # lee la versión de ruff de pyproject.toml
          version-file: pyproject.toml
