name: SonarCloud Scan

on:
  push:
    branches: [master]
  pull_request:

jobs:
  sonar:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java (requisito SonarScanner)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Cache Sonar packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          organization: tuOrgEnSonarCloud
          projectKey: tuUsuario_tuRepo
          token: ${{ secrets.SONAR_TOKEN }}  # ← tu token
